### ISSUE TITLE
Integrity API error on Emulator as well as on a physical device

### ISSUE THREAD

**Issue by hippedorange22** [cashfree/flutter-cashfree-pg-sdk#11]
whenever i hit the pay method, i'm routed to CF payment view and i see payment options but when i pay using a sandbox upi id, this error is being caught.

- Already have app registered on App Check on Firebase.
- Already have the app deployed on Google Play
- Tried with a debug Appcheck key from Firebase
- Tested on Emulator as well as on a real device with Latest Google play Installed
- I'm trying this in SandBox environment

`E/com.cashfree.pg.core.hidden.payment.handler.GooglePlayIntegrityHandler(26681): {"status":"FAILED","message":"Integrity API is not available.The Play Store version might be old, try updating it.","code":"payment_failed","type":"request_failed"}`

you guys should skip integrity checking in Sandbox mode all together.

**Comment by suhas-cashfree** [comment]
@hippedorange22 Please use the latest version 2.0.3+6 and try again

**Comment by suhas-cashfree** [comment]
Closing this issue, as it is resolved. Please create a new issue if it still persists.
