### ISSUE TITLE
Blank screen coming in flutter web

### ISSUE THREAD

**Issue by sourabhsdx** [cashfree/flutter-cashfree-pg-sdk#12]
A blank white screen is coming in flutter web and working fine on android.
<img width="984" alt="Screenshot 2022-12-29 at 10 08 43 AM" src="https://user-images.githubusercontent.com/40622967/209904335-66a9b6da-3e93-4c21-9237-e49b0846a0a9.png">

**Comment by suhas-cashfree** [comment]
@sourabhsdx Please use the latest version 2.0.3+6 and try again

**Comment by suhas-cashfree** [comment]
Closing this issue, as it is resolved. Please create a new issue if it still persists.
