### ISSUE TITLE
android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1

### ISSUE THREAD

**Issue by JayMoliya33** [cashfree/flutter-cashfree-pg-sdk#14]
Hi team,

i am getting SQLiteException exception when app is opened.

Plugin version: 2.0.3+6 

Log

E/AndroidRuntime(24564): android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1 E/AndroidRuntime(24564): 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540) E/AndroidRuntime(24564): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414) E/AndroidRuntime(24564): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340) E/AndroidRuntime(24564): 	at com.cashfree.pg.analytics.database.CFDatabaseService.lambda$checkIfPaymentsPresent$3$CFDatabaseService(Unknown Source:2) E/AndroidRuntime(24564): 	at com.cashfree.pg.analytics.database.-$$Lambda$CFDatabaseService$DscKZq0oUzPPdCcoRl_XPVTLWpg.run(Unknown Source:4) E/AndroidRuntime(24564): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) E/AndroidRuntime(24564): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) E/AndroidRuntime(24564): 	at java.lang.Thread.run(Thread.java:1012)

**Comment by suhas-cashfree** [comment]
Hi @JayMoliya33 do you have "cashfree_pg" also integrated in your application ?

**Comment by JayMoliya33** [comment]
> Hi @JayMoliya33 do you have "cashfree_pg" also integrated in your application ?

Yes @suhas-cashfree

**Comment by suhas-cashfree** [comment]
Hi @JayMoliya33 please remove "cashfree_pg" and do a clean build and use only the new one.

**Comment by JayMoliya33** [comment]
Solved. Thanks @suhas-cashfree.
