### ISSUE TITLE
After completion of  payment success/failure , it  shows request invalid error in iOS platform

### ISSUE THREAD

**Issue by ibcdevteam** [cashfree/flutter-cashfree-pg-sdk#15]
Hi team,

We are facing payment issue in IOS  platform, but the same is working in Android devices. After payment success/failure showing REQUEST_INVALID error page

**Version:**
`flutter_cashfree_pg_sdk: ^2.0.3+6`

**Environment:**
`SANDBOX`

Please find the attached screenshot.
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-09 at 13 55 41](https://user-images.githubusercontent.com/78359828/211268661-ee95b451-d3ee-4e0b-9a38-3e7a9e2c8f3b.png)

**Comment by suhas-cashfree** [comment]
Hi @ibcdevteam Is this specific to any payment mode ?

**Comment by ibcdevteam** [comment]
Hi @suhas-cashfree, We are facing issue in all payment mode(CARD, NETBANKING and UPI).

**Comment by suhas-cashfree** [comment]
Hi @ibcdevteam please write to care@cashfree.com from your registered email ID. We will help you out

**Comment by suhas-cashfree** [comment]
Closing this for now. Please create a new ticket if the issue still persists
