### ISSUE TITLE
android_package_not_approved error in real device for Wallet, UPI, Netbanking etc.. 

### ISSUE THREAD

**Issue by abhishek-joflee** [cashfree/flutter-cashfree-pg-sdk#19]
Version:
`flutter_cashfree_pg_sdk: ^0.0.1+1`

Environment:
`PRODUCTION`

**onError** function is getting called & **CFErrorResponse** obect is 👇 

```
{
    'code': android_package_not_approved,
    'status': FAILED,
    'message': com.huft.app is not enabled or approved. Please reach out to care@cashfree.com.,
}
```

NOTE: Same code is working on iOS simulator !!

**Comment by suhas-cashfree** [comment]
Hi @abhishek-joflee please write to care@cashfree.com or to your account manager to get your app whitelisted

**Comment by suhas-cashfree** [comment]
Hi @abhishek-joflee also please update the SDK to latest version
