### ISSUE TITLE
 UPI Intent flow

### ISSUE THREAD

**Issue by knightowlRaising** [cashfree/flutter-cashfree-pg-sdk#24]
Not able to do UPI Intent flow, have to add UPI Id again for the payments. As _Drop Checkout flow_ and _UPI Intent flow_ discussed in the native Android doc, not covered in the Flutter doc.

**Comment by suhas-cashfree** [comment]
Hi @knightowlRaising, Intent is part of drop checkout.

**Comment by knightowlRaising** [comment]
Thanks @suhas-cashfree for clarifying it. But I'm not able to select UPI apps directly, have to enter UPI Id after choosing one of the options.

**Comment by knightowlRaising** [comment]
I am not able to select UPI Mode, how can I select UPI mode, by default it is raising a collect request.

**Comment by suhas-cashfree** [comment]
Add the permissions present here in Android manifest and try https://docs.cashfree.com/docs/android-sdk#upi-intent

**Comment by knightowlRaising** [comment]
Hi @suhas-cashfree I have tried this and then we launched the app on Prod, but still not working. 

`<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="upi" android:host="pay"/>
    </intent>
    <package android:name="com.android.chrome" />
</queries>`

Added the above code in Manifest.

**Comment by suhas-cashfree** [comment]
Hi @knightowlRaising
There is web checkout option too. Can you try with that

**Comment by knightowlRaising** [comment]
We have tried web checkout as well and got the same thing. Instead of taking me to the UPI app directly, it's asking me to enter UPI Id. Please refer attached screenshot below. 1st Screenshot is web and 2nd is App based.
<p>
<img src="https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/78794679/337b11fb-64c6-4898-bbc7-a3df8c94f48c" width= 250/>
<img src="https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/78794679/fc4ed4cb-091a-45b8-a2c4-f6ec8386f5b8" width= 250/>
</p>

**Comment by suhas-cashfree** [comment]
Please write to care@cashfree.com

**Comment by knightowlRaising** [comment]
@suhas-cashfree the issue is resolved. Thanks for the support 🎉

**Comment by tailoristic** [comment]
@knightowlRaising What was the solution?
