### ISSUE TITLE
After completion of payment success/failure it is stuck on that bottom sheet

### ISSUE THREAD

**Issue by Jagdeepsingh8562** [cashfree/flutter-cashfree-pg-sdk#27]
Hi Team,

We are facing a payment issue, After payment success/failure it shows the response but it does not navigate back to the app screen
package version: `flutter_cashfree_pg_sdk: ^2.0.14+18`
ENV: `SANDBOX`
I've included for you the attached screenshots.
1. <img width="377" alt="Screenshot 2023-08-30 at 2 09 42 PM" src="https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/35945331/42134bff-be63-413e-b1a3-af13351fbbb2">

2. <img width="380" alt="Screenshot 2023-08-30 at 2 10 20 PM" src="https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/35945331/f1caef60-732e-424e-92d9-218fc53366f2">

**Comment by suhas-cashfree** [comment]
Hi @Jagdeepsingh8562 
Does your order create api have a "return_url" in it ?
If so please remove it for mobile sdk payments

**Comment by Jagdeepsingh8562** [comment]
Hi @suhas-cashfree Thanks after the return_url is coming null, it is working

**Comment by Jagdeepsingh8562** [comment]
Please add this Flutter Integration documentation as well
