### ISSUE TITLE
Error in cash free payment 

### ISSUE THREAD

**Issue by chintanmahant** [cashfree/flutter-cashfree-pg-sdk#3]
Hello , today i m facing error in sandbox environment , onError() method is calling and giving msg as **'onError : {"message":"Internal Server Error"}'**, please check 

E/ConfigRequestHandler(10578): onError : {"message":"Internal Server Error"}
I/CFErrorResponse(10578): getString failed for key 'status'.
I/CFErrorResponse(10578): getString failed for key 'code'.
I/CFErrorResponse(10578): getString failed for key 'type'.
W/System.err(10578): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/System.err(10578): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/System.err(10578): 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/System.err(10578): 	at org.json.JSONObject.<init>(JSONObject.java:164)
W/System.err(10578): 	at org.json.JSONObject.<init>(JSONObject.java:181)
W/System.err(10578): 	at com.cashfree.pg.ui.hidden.persistence.CFUIPersistence.getConfigData(CFUIPersistence.java:41)
W/System.err(10578): 	at com.cashfree.pg.ui.hidden.repo.ConfigRepo$2.onFailure(ConfigRepo.java:62)
W/System.err(10578): 	at com.cashfree.pg.ui.hidden.network.ConfigRequestHandler.onError(ConfigRequestHandler.java:63)
W/System.err(10578): 	at com.cashfree.pg.network.GETApi.makeApiCall(GETApi.java:84)
W/System.err(10578): 	at com.cashfree.pg.network.NetworkRequest.lambda$execute$1$NetworkRequest(NetworkRequest.java:62)
W/System.err(10578): 	at com.cashfree.pg.network.-$$Lambda$NetworkRequest$TyAM803R7KEj5hZzpPUf-gZLIb4.run(Unknown Source:8)
W/System.err(10578): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(10578): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(10578): 	at java.lang.Thread.run(Thread.java:919)

**Comment by suhas-cashfree** [comment]
Hi @chintanmahant 
Is it only in SANDBOX or is it happening in PRODUCTION as well ?

**Comment by chintanmahant** [comment]
Hello, no i haven't tried PRODUCTION yet , i have tried SANDBOX and in that error is coming

**Comment by suhas-cashfree** [comment]
Should be working now. If the issue still persists, please write to care@cashfree.com with the email that you use to login to Cashfree

**Comment by suhas-cashfree** [comment]
Closing this for now. Please write to care@cashfree.com if the issue still persists
