### ISSUE TITLE
When i run flutter pub add flutter_cashfree_pg_sdk and restart app then it crash everytime.

### ISSUE THREAD

**Issue by Harshhvermaa** [cashfree/flutter-cashfree-pg-sdk#41]
FATAL EXCEPTION: pool-26-thread-1
E/AndroidRuntime(20646): Process: <package name>, PID: 20646
E/AndroidRuntime(20646): android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
E/AndroidRuntime(20646): 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540)
E/AndroidRuntime(20646): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
E/AndroidRuntime(20646): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
E/AndroidRuntime(20646): 	at com.cashfree.pg.analytics.database.CFDatabaseService.lambda$checkIfPaymentsPresent$3$com-cashfree-pg-analytics-database-CFDatabaseService(Unknown Source:2)
E/AndroidRuntime(20646): 	at com.cashfree.pg.analytics.database.CFDatabaseService$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(20646): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(20646): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20646): 	at java.lang.Thread.run(Thread.java:923)

**Comment by Harshhvermaa** [comment]
I done this multiple times even remove pubspec.lock and re run the whole app after uninstall it but i still got same error.
App crash everytime whenever i try to open it.

**Comment by suhas-cashfree** [comment]
Was it working before this version ?

**Comment by suhas-cashfree** [comment]
We had one older version of sdk called "cashfree_pg". If you have it in your dependencies, please remove that

**Comment by Harshhvermaa** [comment]
Thanks solved.
I want to show all upi apps and when i click on any app they redirect to
that app.

**Comment by suhas-cashfree** [comment]
Please check this example
https://pub.dev/packages/flutter_cashfree_pg_sdk/example

You have to follow the same drill as in old sdk.
In the init method, get the list of installed apps using 

```
CFUPIUtils().getUPIApps().then((value) {
      print(value);
      for(var i = 0; i < (value?.length ?? 0); i++) {
        var a = value?[i]["id"] as String ?? "";
        if(a.contains("phonepe")) {
          selectedId = value?[i]["id"];
        }
      }
    });
```

Then use this

```
upiIntentPay() async {
    try {
      var session = createSession();
      var upi = CFUPIBuilder().setChannel(CFUPIChannel.INTENT).setUPIID(selectedId).build();
      var upiPayment = CFUPIPaymentBuilder().setSession(session!).setUPI(upi).build();
      cfPaymentGatewayService.doPayment(upiPayment);
    } on CFException catch (e) {
      print(e.message);
    }
  }
```

selectedId => The clicked app's id, which you will get in get installed apps method
