### ISSUE TITLE
Unable to build signedapk for release it is showing error because of cashfreee

### ISSUE THREAD

**Issue by YugalYadav09** [cashfree/flutter-cashfree-pg-sdk#42]
![cashfree](https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/148444961/7bcecd05-2c9a-458f-b78a-111f70966656)

###
Please help me out we need to release the app in no short time

**Comment by suhas-cashfree** [comment]
Hi
Please update your compileSdkVersion and the. Flutter clean and then build the apk and try

**Comment by YugalYadav09** [comment]
That was done done still the same issue

**Comment by YugalYadav09** [comment]
and have been trying to build from flutter sdk 3.7. Please help me.
Thanks and regards
Yugal

**Comment by suhas-cashfree** [comment]
What is compileSdkVersion set in Android gradle file ?

**Comment by YugalYadav09** [comment]
34

**Comment by suhas-cashfree** [comment]
Is this still happening ?

**Comment by suhas-cashfree** [comment]
Closing this. Please create a new issue if it still persists.
