### ISSUE TITLE
Unable to build due to flutter_cashfree_pg_sdk

### ISSUE THREAD

**Issue by 0001arunsharma** [cashfree/flutter-cashfree-pg-sdk#46]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':flutter_cashfree_pg_sdk'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@22fdc1a6 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':flutter_cashfree_pg_sdk'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 654ms
Exception: Gradle task assembleDevDebug failed with exit code 1

Have tried flutter clean but still build is throwing same error:

Flutter env : sdk: '>=3.0.3 <4.0.0'
targetSdkVersion 34

**Comment by 0001arunsharma** [comment]
Just to update, I have forked the repo and made below changes to android/build and this issue is fixed, Hoping it to fix by cashfree soon . Please note the changes i have made is only for testing:

android {
    namespace "com.cashfree.flutter_cashfree_pg_sdk" // i have added this line 
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 19
    }
}

**Comment by suhas-cashfree** [comment]
Hi @0001arunsharma Can you try by changing compileSdkVersion to 33 ?

**Comment by suhas-cashfree** [comment]
Added this namespace and is available in the newer version @0001arunsharma 
Closing this ticket, please raise a new one if the issue still persists
