### ISSUE TITLE
 App should be installed from play store or another whitelisted app store.

### ISSUE THREAD

**Issue by pks050505** [cashfree/flutter-cashfree-pg-sdk#49]
when we use cashfree payment gateway in production then show this error message

onError : {"message":"NOT_AVAILABLE is not a trusted source. App should be installed from play store or another whitelisted app store.","code":"installer_package_not_approved","type":"feature_not_enabled"}
and my app package name whitelisted in cashfree website

**Comment by suhas-cashfree** [comment]
Please release the app in beta channel for internal testing in app store, then you can test it in production environment

**Comment by pks050505** [comment]
worded
