### ISSUE TITLE
subscription feature in this sdk ?

### ISSUE THREAD

**Issue by yogeshelevn** [cashfree/flutter-cashfree-pg-sdk#50]
Hey, I am integrating this SDK into our Flutter app. I wanted to know if this SDK provides features for subscription/recurring payments. if this Sdk provide this feature. I would like to explore it please share relevant documentation.

**Comment by suhas-cashfree** [comment]
Hi @yogeshelevn 
This sdk is only for payment gateway.
For subscription, check this -> https://docs.cashfree.com/docs/subscriptions

You can also reach out to care@cashfree.com for more information / queries
