### ISSUE TITLE
OnError method not getting called when back button is pressed

### ISSUE THREAD

**Issue by dheerajverma009** [cashfree/flutter-cashfree-pg-sdk#51]
OnError method not getting called when back button is pressed.

Using flutter_cashfree_pg_sdk: ^2.1.1+31

For flutter version greatr than 3.16, OnError method not getting called.
But i have test only for Flutter version - 3.16.3 & 3.16.8

https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/147540729/b3b9adbc-470c-45e6-acd4-d1863f1cd497

Expected result
But when using below flutter version, works fine
Flutter version - 3.13.9

https://github.com/cashfree/flutter-cashfree-pg-sdk/assets/147540729/b35ff85b-0a00-4e55-af8f-382e69fb2404

 Code
```
class PaymentWidget extends StatefulWidget {
  const PaymentWidget({super.key});

  @override
  State<PaymentWidget> createState() => _PaymentWidgetState();
}

class _PaymentWidgetState extends State<PaymentWidget> {
  String paymentStatus = 'PaymentStatus None';
  final String _orderId = '';
  final String _paymentSessionId = '';
  static const CFEnvironment _environment = CFEnvironment.SANDBOX;

  final CFPaymentGatewayService _cfPaymentGatewayService =
      CFPaymentGatewayService();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text(
              paymentStatus,
              style: TextStyle(
                fontSize: 20,
              ),
            ),
            SizedBox(
              height: 30,
            ),
            ElevatedButton(
              onPressed: onPressed,
              child: const Text(
                'Make Payment',
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> onPressed() async {
    _cfPaymentGatewayService.setCallback(_verifyPayment, _onError);
    await _makePayment();
  }

  Future<void> _verifyPayment(String orderId) async {
    setState(() {
      paymentStatus = 'Payment Success';
    });
  }

  Future<void> _onError(
    CFErrorResponse errorResponse,
    String orderId,
  ) async {
    setState(() {
      paymentStatus = 'Payment Error';
    });
  }

  Future _makePayment() async {
    CFSession session = CFSessionBuilder()
        .setEnvironment(_environment)
        .setOrderId(_orderId)
        .setPaymentSessionId(_paymentSessionId)
        .build();
    var cfWebCheckout =
        CFWebCheckoutPaymentBuilder().setSession(session).build();
    _cfPaymentGatewayService.doPayment(cfWebCheckout);
  }
}
```

**Comment by dheerajverma009** [comment]
@suhas-cashfree

**Comment by suhas-cashfree** [comment]
This is working. Are you still facing any issue ?

**Comment by dheerajverma009** [comment]
yes, issue is still there. 
One ore thing i forgot to include one piece of code. 
Also add android:enableOnBackInvokedCallback="true" in manifest file.  

https://docs.flutter.dev/release/breaking-changes/android-predictive-back#supporting-predictive-back

**Comment by kishan-cashfree** [comment]
@dheerajverma009 
Can you confirm whether you are running on Android 14 devices?

**Comment by dheerajverma009** [comment]
Yes I am
I was able to test this issue in android 13,and 14. In other versions it works fine.

According to me it is happening when predictive back gestures support is enabled in android. If not enabled it is working fine.

**Comment by kishan-cashfree** [comment]
By-default `predictive back gestures` is available from Android 14. 

In Android 13, if some enable thro developer option then only it will be enabled else on Android 13 normal back button flow will work.

**Comment by dheerajverma009** [comment]
@kishan-cashfree  ok, will look into it for android 13

**Comment by dheerajverma009** [comment]
@kishan-cashfree 
so do you mean we do not have to add android:enableOnBackInvokedCallback="true" in manifest file for android 14 ?

**Comment by kishan-cashfree** [comment]
@dheerajverma009 
https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#opt-predictive
If you don't add, by-default it will be false which means it will continue to work as expected as in previous version. 

when you add it in manifest  as true then this will be enable.

**Comment by dheerajverma009** [comment]
@kishan-cashfree 
I got it. So as issue descried above, is it a bug or not??

**Comment by kishan-cashfree** [comment]
@dheerajverma009 
It's not a bug, rather, we will consider it a feature request.

**Comment by dheerajverma009** [comment]
ok, so do i have to raise another issue as feature request for above issue?
And can you also can give update till when this feature will be available.
