### ISSUE TITLE
Domain whitelist Approved on merchant account, but Throws Broken Link error when opening the cashfree pg in flutter android

### ISSUE THREAD

**Issue by zaid-debug** [cashfree/flutter-cashfree-pg-sdk#56]
I have integrated cashfree pg in my flutter project, the domain name is approved on merchant account, but when I proceed payment in my app, the cashfree screen shows error, that the domain name "com.synilogic.asthajyotish" is not whitelisted. 
dependencies:
    flutter_cashfree_pg_sdk: ^2.1.3+33

 //Cashfree --->
  CFSession? createSession() {
    try {
      if (orderId.value == null || sessionId.value == null) {
        print('Order ID or Session ID is null');
        return null;
      } else {
        print("orderId:::${orderId.value}");
        print("sessionId:::${sessionId.value}");
      }
      var session = CFSessionBuilder()
          .setEnvironment(CFEnvironment.PRODUCTION)
          .setOrderId(orderId.value!)
          .setPaymentSessionId(sessionId.value!)
          .build();
      return session;
    } on CFException catch (e) {
      print(e.message);
    }
    return null;
  }

  webCheckout() async {
    try {
      var session = createSession();
      var cfWebCheckout = CFWebCheckoutPaymentBuilder().setSession(session!).build();
      CFPaymentGatewayService().doPayment(cfWebCheckout);
    } on CFException catch (e) {
      print(e.message);
    }
  }

  void onVerify(String orderId) {
    /**
     * Verify Payment status from the backend using order Status API
     */
    print('success:::');
    // isPaymentInProgress.value = false;
    isPurchaseSuccess.value = true;
  }

  void onError(CFErrorResponse errorResponse, String orderId) {
    /**
     * Configure Error callback
     */
    print('error:::${errorResponse.getMessage()}, $orderId');
    // isPaymentInProgress.value = false;
  }
  // --->

**Comment by rajnandan1** [comment]
It takes 1 hour for changes to take affect, also can you share a screenshot

**Comment by zaid-debug** [comment]
It is whitelisted from many days, still the error shows. Below are the
attachment of screenshots

**Comment by zaid-debug** [comment]
Actually, the issue was our package name was yet to be approved, although the domain name was approved. Hence the issue resolved when package name whitelisted. Hence closing the issue.
