### ISSUE TITLE
UPI apps not showing in Android 15

### ISSUE THREAD

**Issue by rishav3five8** [cashfree/flutter-cashfree-pg-sdk#57]
With the Android 15 release, when i try to checkout payment bill then UPI apps not visible, white blank page coming. Below android 15, its working fine.

**Comment by kishan-cashfree** [comment]
@rishav3five8 Can you please help with your integration 
Also, add any video if possible

**Comment by rishav3five8** [comment]
@kishan-cashfree Integration part i did from below documentation:

(https://pub.dev/packages/flutter_cashfree_pg_sdk)

And its working fine below android 15 devices. So integration part any specific for android 15?

**Comment by kishan-cashfree** [comment]
@rishav3five8 Can you share the video

**Comment by rishav3five8** [comment]
![cash_free_upi_white_screen](https://github.com/user-attachments/assets/e4098bf7-ae70-47f3-b038-000289c03706)

**Comment by rishav3five8** [comment]
@kishan-cashfree I can not share video but i shared you screenshot for white blank screen android 15

**Comment by kishan-cashfree** [comment]
@rishav3five8 No specific integration is required for android 15. 
We have also tested it from our side and it working fine .

Can you join this call?, will resolve the issue over the call
https://meet.google.com/fdc-vobp-afv?authuser=0&hl=en&hs=203

**Comment by kishan-cashfree** [comment]
In Your emulator, Make sure you have UPI apps installed
Can you confirm if is there any UPI app available in Emulator?

**Comment by kishan-cashfree** [comment]
Can you install this sample UPI app and let us know if this is also coming under UPI section?
https://docs.cashfree.com/docs/cashfree-upi-intent-simulator-apk

**Comment by kishan-cashfree** [comment]
@rishav3five8 
Can you install this sample UPI app and let us know if this is also coming under UPI section?
https://docs.cashfree.com/docs/cashfree-upi-intent-simulator-apk

**Comment by rishav3five8** [comment]
> @rishav3five8 No specific integration is required for android 15. We have also tested it from our side and it working fine .
> 
> Can you join this call?, will resolve the issue over the call https://meet.google.com/fdc-vobp-afv?authuser=0&hl=en&hs=203

@kishan-cashfree can we connect now?

**Comment by kishan-cashfree** [comment]
@rishav3five8 Yes

**Comment by rishav3five8** [comment]
@kishan-cashfree can you join link

**Comment by kishan-cashfree** [comment]
@rishav3five8 Are you joining the call??

**Comment by kishan-cashfree** [comment]
Since there was no UPI app installed & ready for payment, so no UPI lists were shown in the UI. hence closing this ticket. Please reopen if you again face this issue.


You can join our discord channel for quicker resolution. 
https://discord.gg/g6WhD7H9

**Comment by rishav3five8** [comment]
@kishan-cashfree can join again same link

**Comment by rishav3five8** [comment]
@kishan-cashfree after transaction also UPI apps not visible

**Comment by rishav3five8** [comment]
@kishan-cashfree issue still not resolved , i want to open it

**Comment by rishav3five8** [comment]
@kishan-cashfree can we connect once more, still facing issue

**Comment by kishan-cashfree** [comment]
This is tested & verified with @rishav3five8.
