### ISSUE TITLE
Android 15 UPI apps not visible even after bank transaction setup on device.

### ISSUE THREAD

**Issue by rishav3five8** [cashfree/flutter-cashfree-pg-sdk#58]
UPI apps not visible even after bank transaction setup on device (physical as well as on emulator)

**Comment by suhas-cashfree** [comment]
Hey Hi @rishav3five8 
There is a method in flutter sdk to fetch all installed apps
Can you call that method in any of your screen and check if you are getting the installed applications

**Comment by suhas-cashfree** [comment]
https://github.com/cashfree/flutter-cashfree-pg-sdk/blob/main/example/lib/main.dart#L69

`CFUPIUtils().getUPIApps().then((value) {
      print("value");
      print(value);
      for(var i = 0; i < (value?.length ?? 0); i++) {
        var a = value?[i]["id"] as String ?? "";
        if(a.contains("cashfree")) {
          selectedId = value?[i]["id"];
        }
      }
    });`

**Comment by rishav3five8** [comment]
@suhas-cashfree I think there is no issue of showing apps, bceause i am able to show Cashfree Test UPI app . But other apps like gpay, phonePe, Paytm not showing.

**Comment by suhas-cashfree** [comment]
So the apps are not shown in the drop sdk flow which you are using (this is deprecated)
We recommend you move to checkout flow.
Can you check by calling this method to see if you are getting the list of installed apps -> `CFUPIUtils().getUPIApps()`

**Comment by rishav3five8** [comment]
@suhas-cashfree can we connect on meet link 
To join the video meeting, click this link: https://meet.google.com/eus-rbfd-gpa
Otherwise, to join by phone, dial +1 601-640-0424 and enter this PIN: 361 726 641#
To view more phone numbers, click this link: https://tel.meet/eus-rbfd-gpa?hs=5

**Comment by kishan-cashfree** [comment]
@rishav3five8  Thanks for coming over to call.
We have verified & tested it in Android 15 and tried it with `PhonePe` & `PayTm`. Both apps are visible & working as expected. So closing this ticket.

You can join our discord channel for quicker resolution.
https://discord.gg/g6WhD7H9
