### ISSUE TITLE
On Flutter Web Callback Functions not working

### ISSUE THREAD

**Issue by siman302** [cashfree/flutter-cashfree-pg-sdk#59]
I try to implement the cashflow on the flutter web.
Everything is working fine, expect then call back functions.

**Note:**
I am testing on the **sandbox** and so I think **domain restriction** is not an issue, because I am developer from **Pakistan** 

`  // Verify Payment Callback
  Future<void> verifyPayment(String orderId) async {
    final verifyUrl = "${_cashfreeBaseUrl}pg/orders/$orderId";

    try {
      final response = await http.get(
        Uri.parse(verifyUrl),
        headers: {
          'Content-Type': 'application/json',
          'x-client-id': _apiKey,
          'x-client-secret': _secretKey,
          'x-api-version': '2023-08-01',
        },
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        log("UPI Payment verification successful for Order ID: $orderId");
        // Add further handling for successful payment
      } else {
        log("Failed to verify UPI payment: ${response.statusCode} - ${response.body}");
      }
    } catch (e) {
      log("Error while verifying UPI payment: $e");
    }
  }

  // Error Callback
  void onError(CFErrorResponse errorResponse, String orderId) {
    log("Payment error for Order ID: $orderId");
    log("Error message: ${errorResponse.getMessage()}");
    // Add further error handling logic
  }

  // Web Checkout Function
  Future<void> webCheckout(CFSession session) async {
    try {
      // Build the checkout object with the session
      var cfWebCheckout =
          CFWebCheckoutPaymentBuilder().setSession(session).build();

      // Set the callback before initiating the payment
      _cfPaymentGatewayService.setCallback(verifyPayment, onError);

      log('Initiating payment...');
      _cfPaymentGatewayService.doPayment(cfWebCheckout);
    } on CFException catch (e) {
      log("CFException during payment: ${e.message}");
    } catch (e) {
      log("Unexpected error during payment: $e");
    }
  }`

verifyPayment and onError functions are not invoke, when I check it in details in the **cfpaymentgatewayservice.dart** file, I found that in function doPayment, the **invokeMethod("doWebPayment")** return the null value instantly, not wait until the **doWebPayment** finish execution that why verifyPayment and onError functions not call. Kindly fix the **doWebPayment functions**, Thanks.

`doPayment(CFPayment cfPayment) {
    if (verifyPayment == null || onError == null) {
      throw CFException(CFExceptionConstants.CALLBACK_NOT_SET);
    }

    Map<String, dynamic> data = <String, dynamic>{};

    if (cfPayment is CFCardPayment) {
      CFCardPayment cfCardPayment = cfPayment;
      _initiateCardPayment(cfCardPayment);
    } else {
      if (cfPayment is CFDropCheckoutPayment) {
        CFDropCheckoutPayment dropCheckoutPayment = cfPayment;
        data = _convertToMap(dropCheckoutPayment);
      } else if (cfPayment is CFWebCheckoutPayment) {
        CFWebCheckoutPayment webCheckoutPayment = cfPayment;
        data = _convertToWebCheckoutMap(webCheckoutPayment);
      } else if (cfPayment is CFUPIPayment) {
        CFUPIPayment cfupiPayment = cfPayment;
        data = _convertToUPItMap(cfupiPayment);
      } else if (cfPayment is CFNetbankingPayment) {
        CFNetbankingPayment cfNetbankingPayment = cfPayment;
        data = _convertToNetbankingMap(cfNetbankingPayment);
      }

      // Create Method channel here
      MethodChannel methodChannel =
          const MethodChannel('flutter_cashfree_pg_sdk');
      if (cfPayment is CFDropCheckoutPayment) {
        methodChannel.invokeMethod("doPayment", data).then((value) {
          responseMethod(value);
        });
      } else if (cfPayment is CFWebCheckoutPayment) {
        methodChannel.invokeMethod("doWebPayment", data).then((value) {
          responseMethod(value);
        });
      } else if (cfPayment is CFUPIPayment) {
        methodChannel.invokeMethod("doUPIPayment", data).then((value) {
          responseMethod(value);
        });
      } else if (cfPayment is CFNetbankingPayment) {
        methodChannel.invokeMethod("doNetbankingPayment", data).then((value) {
          responseMethod(value);
        });
      }
    }
  }`

**Comment by suhas-cashfree** [comment]
Are you getting any error here ?

`  // Set the callback before initiating the payment
  _cfPaymentGatewayService.setCallback(verifyPayment, onError);

  log('Initiating payment...');
  _cfPaymentGatewayService.doPayment(cfWebCheckout);
} on CFException catch (e) {
  log("CFException during payment: ${e.message}");
} catch (e) {
  log("Unexpected error during payment: $e");
}`

**Comment by siman302** [comment]
yes, verifyPayment, onError functions not invoke when payment is made even failed or successfully.

**Comment by siman302** [comment]
My service File Code.

`import 'dart:convert';
import 'dart:developer';
import 'package:flutter_cashfree_pg_sdk/api/cferrorresponse/cferrorresponse.dart';
import 'package:flutter_cashfree_pg_sdk/api/cfpayment/cfwebcheckoutpayment.dart';
import 'package:flutter_cashfree_pg_sdk/api/cfpaymentgateway/cfpaymentgatewayservice.dart';
import 'package:flutter_cashfree_pg_sdk/api/cfsession/cfsession.dart';
import 'package:flutter_cashfree_pg_sdk/utils/cfenums.dart';
import 'package:flutter_cashfree_pg_sdk/utils/cfexceptions.dart';
import 'package:http/http.dart' as http;

class CashfreePaymentService {
  static const String _cashfreeBaseUrl = "https://sandbox.cashfree.com/";
  static const String _apiKey = "TEST1015993476698750d6864430332543995101";
  static const String _secretKey =
      "cfsk_ma_test_4b1dceb4b3914527c26a16af3a67a328_40cd1f52";
  final CFPaymentGatewayService _cfPaymentGatewayService =
      CFPaymentGatewayService();

  // Create Order Function
  Future<Map<String, dynamic>> createOrder(
    double amount,
    String orderId,
    String customerEmail,
    String customerName,
    String customerId,
    String customerPhone,
  ) async {
    const url = "${_cashfreeBaseUrl}pg/orders"; // Live URL for production

    final body = jsonEncode({
      "order_amount": amount.toStringAsFixed(2),
      "order_currency": "INR",
      "customer_details": {
        "customer_id": customerId,
        "customer_name": customerName,
        "customer_email": customerEmail,
        "customer_phone": customerPhone
      },
      "order_meta": {"return_url": "https://google.com"}
    });

    try {
      final response = await http.post(
        Uri.parse(url),
        headers: {
          'Content-Type': 'application/json',
          'x-client-id': _apiKey,
          'x-client-secret': _secretKey,
          'x-api-version': '2023-08-01',
        },
        body: body,
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return {
          "orderId": data['cf_order_id'],
          "paymentSessionId": data['payment_session_id'],
        };
      } else {
        throw Exception(
            "Failed to initiate payment: ${response.statusCode} - ${response.body}");
      }
    } catch (e) {
      log("Unexpected error: $e");
      throw Exception("Unexpected error: $e");
    }
  }

  // Create Session
  CFSession? createSession(Map<String, dynamic> data) {
    try {
      var session = CFSessionBuilder()
          .setEnvironment(CFEnvironment.SANDBOX)
          .setOrderId(data['orderId'])
          .setPaymentSessionId(data['paymentSessionId'])
          .build();
      return session;
    } on CFException catch (e) {
      throw Exception("Request failed: ${e.message}");
    }
  }

  // Verify Payment Callback
  Future<void> verifyPayment(String orderId) async {
    final verifyUrl = "${_cashfreeBaseUrl}pg/orders/$orderId";

    try {
      final response = await http.get(
        Uri.parse(verifyUrl),
        headers: {
          'Content-Type': 'application/json',
          'x-client-id': _apiKey,
          'x-client-secret': _secretKey,
          'x-api-version': '2023-08-01',
        },
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        log("UPI Payment verification successful for Order ID: $orderId");
        // Add further handling for successful payment
      } else {
        log("Failed to verify UPI payment: ${response.statusCode} - ${response.body}");
      }
    } catch (e) {
      log("Error while verifying UPI payment: $e");
    }
  }

  // Error Callback
  void onError(CFErrorResponse errorResponse, String orderId) {
    log("Payment error for Order ID: $orderId");
    log("Error message: ${errorResponse.getMessage()}");
    // Add further error handling logic
  }

  // Web Checkout Function
  Future<void> webCheckout(CFSession session) async {
    try {
      // Build the checkout object with the session
      var cfWebCheckout =
          CFWebCheckoutPaymentBuilder().setSession(session).build();

      // Set the callback before initiating the payment
      _cfPaymentGatewayService.setCallback(verifyPayment, onError);

      log('Initiating payment...');
      _cfPaymentGatewayService.doPayment(cfWebCheckout);
    } on CFException catch (e) {
      log("CFException during payment: ${e.message}");
    } catch (e) {
      log("Unexpected error during payment: $e");
    }
  }
}
`

**Comment by suhas-cashfree** [comment]
Are you getting any error here -> log("CFException during payment: ${e.message}");

Or here -> log("Unexpected error during payment: $e");

**Comment by siman302** [comment]
No, Not get any error.
verifyPayment and onError functions not invoke.

**Comment by siman302** [comment]
Check the code video.

https://drive.google.com/file/d/1lo4Er_7_psRsZunQuGDdAty3LOqQ8An4/view?usp=sharing

**Comment by suhas-cashfree** [comment]
Hey hi
This is expected behaviour
What you are doing is a redirect flow
You received verify callback as soon as the web page opened.

You have to have a "return_url" when you create the order. So that once the payment is complete, there is a redirection that will happen to that url

Check return url here -> https://docs.cashfree.com/reference/pgcreateorder

**Comment by siman302** [comment]
Yes, I set the return_url, which I send in the request when I get create the order.
That link will open successfully, when payment process in completed, whether it completed or failed.

Still I don't received the callbacks.
@suhas-cashfree

**Comment by suhas-cashfree** [comment]
That’s what I was saying. In this flow, you will not get callbacks. You should check the order status on redirection to your return url. The return url will have order id in query params

**Comment by suhas-cashfree** [comment]
Closing this ticket. Please raise a new one, if the issue still persists

**Comment by siman302** [comment]
Thanks @suhas-cashfree
