### ISSUE TITLE
UPI apps not visible while checkout in iOS

### ISSUE THREAD

**Issue by rishav3five8** [cashfree/flutter-cashfree-pg-sdk#60]
I am unable to see UPI apps while checkout

**Comment by suhas-cashfree** [comment]
Can you share more details ?
A screenshot would help

**Comment by rishav3five8** [comment]
https://github.com/user-attachments/assets/4438eb40-12ad-49f9-8263-1042b3bf0fdd

@suhas-cashfree please check this video

**Comment by rishav3five8** [comment]
@suhas-cashfree happening Devices are iphone 12 and 13.
IOS 17.5.1

But, working fine for my personal device having ios 17.6.1

**Comment by suhas-cashfree** [comment]
Checkout page has not opened at all in the video

**Comment by suhas-cashfree** [comment]
Are you getting any error ?
Are you using upi flow or web checkout ?

**Comment by rishav3five8** [comment]
web checkout

**Comment by rishav3five8** [comment]
actually in debug mode i am not getting any error, and its working fine for our testing team as well, but production user reporting this issue

**Comment by suhas-cashfree** [comment]
Can you show me the working screenshot.
May be the user might not have any upi apps installed in his device

**Comment by rishav3five8** [comment]
@suhas-cashfree we checked with user, user have Gpay and bhim UPI apps in his device

**Comment by suhas-cashfree** [comment]
From the video you have sent, it seems like it is stuck before opening checkout page. seems like an error before opening checkout.
Can you share a working video as well

**Comment by rishav3five8** [comment]
Uploading Screenrecorder-2024-09-16-14-25-10-729.mp4…

**Comment by rishav3five8** [comment]
@suhas-cashfree I shared you working video please check.

**Comment by rishav3five8** [comment]
https://github.com/user-attachments/assets/1ff7ffef-2953-43c6-9eba-8fb9aabf22ff

**Comment by suhas-cashfree** [comment]
This is android. Issue is in ios no ?
Can you share a working demo of ios ?

**Comment by suhas-cashfree** [comment]
Not sure why it's not working.
It will not show only if it's not installed in the device or if permissions are not added

**Comment by rishav3five8** [comment]
@suhas-cashfree which permissions?

**Comment by rishav3five8** [comment]
also according to you, we should use web checkout flow instead of UPI flow but this is not the issue right?

**Comment by suhas-cashfree** [comment]
That is not an issue. We have deprecated the flow you are using. No active development happens there, that's why

**Comment by suhas-cashfree** [comment]
Write a mail to care@cashfree.com
The team will schedule a call to check further if required

**Comment by rishav3five8** [comment]
@suhas-cashfree the issue we are getting in flutter

**Comment by rishav3five8** [comment]
@suhas-cashfree any update , regarding this flutter app issue happening for ios only?

**Comment by suhas-cashfree** [comment]
Hi @rishav3five8 Please write to care@cashfree.com
Not sure why it is happening. 
We can check by scheduling a meeting

**Comment by rishav3five8** [comment]
@suhas-cashfree already mailed for schedule a meeting. So we can schedule today also if possible.

**Comment by rishav3five8** [comment]
@suhas-cashfree that issue we  sort for android but now issue is coming in flutter ios

**Comment by suhas-cashfree** [comment]
Newer version of flutter can you use and try ?

**Comment by suhas-cashfree** [comment]
Is this still happening ?

**Comment by suhas-cashfree** [comment]
Please raise a new ticket if the issue still persists
