### ISSUE TITLE
flutter ios cashfree sdk UPI apps page not loaded, getting crash

### ISSUE THREAD

**Issue by rishav3five8** [cashfree/flutter-cashfree-pg-sdk#63]
flutter ios cashfree sdk UPI apps page not loaded, getting crash in production one of ios device but working fine in debug mode. Please find below attached video

https://github.com/user-attachments/assets/0bd2fa55-9a13-49ba-b90f-50eed408a2e3

**Comment by ashutosh-mulik** [comment]
We are experiencing the same issue with the Cashfree SDK in our Flutter iOS app. The UPI apps page is not loading and crashes on one of our iOS devices, while it works fine in debug mode. Have you found any resolutions for this?

**Comment by rishav3five8** [comment]
@ashutosh-mulik have you found any solution?

**Comment by ashutosh-mulik** [comment]
@rishav3five8 We have contacted the support team and successfully connected with them. The issue has been resolved.
