### ISSUE TITLE
IOS Podspec syntax error

### ISSUE THREAD

**Issue by Renatinaveen** [cashfree/flutter-cashfree-pg-sdk#7]
[!] Invalid `flutter_cashfree_pg_sdk.podspec` file: syntax error, unexpected end-of-input, expecting `end'
...ndency 'CashfreePG', '~> 2.0.1'

Sol: Add "end" in the last line

**Comment by suhas-cashfree** [comment]
This is fixed. Please use version 2.0.1+4

**Comment by Renatinaveen** [comment]
Hi,

I'm trying to test upi id with ***@***.*** and ***@***.***
the timer just runs out but nothing happens. Are there any new upi id's
available?
And also if show more is clicked for more apps and select any app in the
list nothing is happening.

**Comment by suhas-cashfree** [comment]
In test environment, use "testsuccess@gocash" or "testfailure@gocash"

**Comment by suhas-cashfree** [comment]
After selecting an app in show more, there is a pay button below, clicking on that navigation will happen. Please check that once

**Comment by Renatinaveen** [comment]
Hi,

For ***@***.*** before in first version of the SDK it used return
success after a while. Now it just keeps loading and after 5min timer runs
out nothing happens.

For ***@***.*** it supposed show fail but in one version it was
crashing the app. But now after 5min timer it just closes the timer dialog.

**Comment by Renatinaveen** [comment]
Hi,

Attaching a screen recording for your reference. I couldn't find the button
you mentioned.

https://drive.google.com/file/d/1cYXff1lQH0ZlV4dLNurwaEqIbue2CMvn/view?usp=drivesdk

**Comment by Renatinaveen** [comment]
Hey,

The above video link didn't work for me. Please check this.

https://drive.google.com/file/d/1LXbcUohXIAE7uYQla-O7U9IXb3svF5p1/view?usp=drivesdk

**Comment by suhas-cashfree** [comment]
Please try once in PRODUCTION environment for the upi-id flow

**Comment by suhas-cashfree** [comment]
Will let you know about the "Show more apps" in some time

**Comment by Renatinaveen** [comment]
Okay will try and get back.

**Comment by Renatinaveen** [comment]
Hi,

Any update on this?
